#!/bin/bash
set -e

function log {
  printf "\n\033[2m[$(date)]\033[0m -- \033[1m$@\033[0m\n"
}

path_to_libra=$1

if [[ -z "$path_to_libra" ]]

then
  log "Please supply correct parameters"
  exit 1
fi

log "Deploying on production server (server)"

ssh -t root@207.154.201.209 -i $path_to_libra "
  cd apps/doniraj.hr
  git checkout develop
  git pull origin develop
  source ~/.zshrc
  bundle install
  RAILS_ENV=production rails db:migrate:with_data
  RAILS_ENV=production rails assets:precompile
  kill $(lsof -i :3000 -t)
  kill -9 $(lsof -i :3000 -t)
  pkill --pidfile tmp/pids/server.pid
  RAILS_ENV=production rails s -d"