name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: deploy with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd apps/doniraj.hr/
            git stash
            git pull origin develop
            echo "----- Sourcing... -----"
            source ~/.zshrc
            echo "----- Sourced successfully! -----"
            bundle install
            RAILS_ENV=production rails db:migrate:with_data
            RAILS_ENV=production rails assets:precompile
            RAILS_ENV=production puma -C config/puma.rb